In [1]:
import pandas as pd
pd.__version__

'0.17.1'

In [2]:
import numpy as np
import pandas as pd

In [3]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [4]:
data.values

array([ 0.25,  0.5 ,  0.75,  1.  ])

In [5]:
data.index

Int64Index([0, 1, 2, 3], dtype='int64')

In [6]:
data[1]

0.5

In [7]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [8]:
data[1]

0.5

In [9]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Florida     170312  19552860
Illinois    149995  12882135
New York    141297  19651127
Texas       695662  26448193

In [10]:
data['area']

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [11]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [12]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Florida       19552860
Illinois      12882135
New York      19651127
Texas         26448193
dtype: int64

In [13]:
population['California':'Illinois']

California    38332521
Florida       19552860
Illinois      12882135
dtype: int64

In [14]:
pd.Series({2:'a', 1:'b', 3:'c'})

1    b
2    a
3    c
dtype: object

In [15]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b   c
0   1  2 NaN
1 NaN  3   4

In [16]:
pd.DataFrame({'population': population,
              'area': area})

area  population
California  423967    38332521
Florida     170312    19552860
Illinois    149995    12882135
New York    141297    19651127
Texas       695662    26448193

In [17]:
mic = pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

In [18]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.0), (0, 0.0), (0, 0.0)], 
      dtype=[('A', '<i8'), ('B', '<f8')])

In [19]:
mic

foo       bar
a  0.432921  0.700285
b  0.635608  0.914552
c  0.915903  0.778338

In [20]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.0), (0, 0.0), (0, 0.0)], 
      dtype=[('A', '<i8'), ('B', '<f8')])

In [21]:
A['B']

array([ 0.,  0.,  0.])

In [22]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [23]:
ind[1]

3

In [24]:
ind[0]

2

In [25]:
ind[0:3]

Int64Index([2, 3, 5], dtype='int64')

In [26]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
mef = pd.Series({'California':3, "Texas":4, 
                 "New York":5, "Florida":6,
                'Illinois':7})
data = pd.DataFrame({'area':area, 'pop':pop, 'mef':mef})
data

area  mef       pop
California  423967    3  38332521
Florida     170312    6  19552860
Illinois    149995    7  12882135
New York    141297    5  19651127
Texas       695662    4  26448193

In [27]:
data['area']

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [28]:
data.area is data['area']

True

In [29]:
data['density'] = data['pop'] / data['area']

In [30]:
data

area  mef       pop     density
California  423967    3  38332521   90.413926
Florida     170312    6  19552860  114.806121
Illinois    149995    7  12882135   85.883763
New York    141297    5  19651127  139.076746
Texas       695662    4  26448193   38.018740

In [31]:
data.values

array([[  4.23967000e+05,   3.00000000e+00,   3.83325210e+07,
          9.04139261e+01],
       [  1.70312000e+05,   6.00000000e+00,   1.95528600e+07,
          1.14806121e+02],
       [  1.49995000e+05,   7.00000000e+00,   1.28821350e+07,
          8.58837628e+01],
       [  1.41297000e+05,   5.00000000e+00,   1.96511270e+07,
          1.39076746e+02],
       [  6.95662000e+05,   4.00000000e+00,   2.64481930e+07,
          3.80187404e+01]])

In [32]:
data.transpose()

California          Florida         Illinois         New York  \
area       423967.000000    170312.000000    149995.000000    141297.000000   
mef             3.000000         6.000000         7.000000         5.000000   
pop      38332521.000000  19552860.000000  12882135.000000  19651127.000000   
density        90.413926       114.806121        85.883763       139.076746   

                  Texas  
area       695662.00000  
mef             4.00000  
pop      26448193.00000  
density        38.01874

In [33]:
data.values[0]

array([  4.23967000e+05,   3.00000000e+00,   3.83325210e+07,
         9.04139261e+01])

In [34]:
data['area']

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [35]:
data.area.index

Index(['California', 'Florida', 'Illinois', 'New York', 'Texas'], dtype='object')

In [36]:
data

area  mef       pop     density
California  423967    3  38332521   90.413926
Florida     170312    6  19552860  114.806121
Illinois    149995    7  12882135   85.883763
New York    141297    5  19651127  139.076746
Texas       695662    4  26448193   38.018740

In [37]:
data.ix[2:4,'mef':'pop']

mef       pop
Illinois    7  12882135
New York    5  19651127

In [38]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [41]:
df = pd.DataFrame(rng.randint(0,10,(3,4)), columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  1  7  5  1
1  4  0  9  5
2  8  0  9  2

In [47]:
np.sum(ser)

20

In [48]:
np.sqrt(ser)

0    2.449490
1    1.732051
2    2.645751
3    2.000000
dtype: float64

In [49]:
np.sum(df)

A    13
B     7
C    23
D     8
dtype: int64

In [50]:
np.sqrt(df)

A         B         C         D
0  1.000000  2.645751  2.236068  1.000000
1  2.000000  0.000000  3.000000  2.236068
2  2.828427  0.000000  3.000000  1.414214

In [51]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

In [56]:
area

Alaska        1723337
California     423967
Texas          695662
Name: area, dtype: int64

In [55]:
population

California    38332521
New York      19651127
Texas         26448193
Name: population, dtype: int64

In [57]:
population/area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [58]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                 columns=list('AB'))
A

A   B
0  11  19
1   2   4

In [59]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                 columns=list('BAC'))
B

B  A  C
0  2  6  4
1  8  6  1
2  3  8  1

In [60]:
A+B

A   B   C
0  17  21 NaN
1   8  12 NaN
2 NaN NaN NaN

In [61]:
A.add(B, fill_value=np.mean(A.values))

A   B   C
0  17  21  13
1   8  12  10
2  17  12  10

In [62]:
A = rng.randint(10, size=(3, 4))
A

array([[9, 8, 9, 4],
       [1, 3, 6, 7],
       [2, 0, 3, 1]])

In [63]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-8, -5, -3,  3],
       [-7, -8, -6, -3]])

In [65]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -8 -5 -3  3
2 -7 -8 -6 -3

In [68]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0  1  0  1 -4
1 -2  0  3  4
2  2  0  3  1

In [69]:
halfrow = df.iloc[0, ::2]
halfrow

Q    9
S    9
Name: 0, dtype: int64

In [70]:
df - halfrow

Q   R  S   T
0  0 NaN  0 NaN
1 -8 NaN -3 NaN
2 -7 NaN -6 NaN