In [1]:
import numpy as np

In [2]:
x = np.array([[1,2,3],[2,3,4]])

In [3]:
x

array([[1, 2, 3],
       [2, 3, 4]])

In [4]:
x.ndim

2

In [5]:
x.shape

(2, 3)

In [6]:
x

array([[1, 2, 3],
       [2, 3, 4]])

In [7]:
x[0,0]

1

In [8]:
x[:,1]

array([2, 3])

In [13]:
x[0::0,::1]

ValueError: slice step cannot be zero

In [14]:
x

array([[1, 2, 3],
       [2, 3, 4]])

In [15]:
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [16]:
c_array = np.random.rand(1000,1000)

In [17]:
c_array

array([[ 0.23998508,  0.11250528,  0.19466276, ...,  0.10422653,
         0.19806809,  0.27674198],
       [ 0.08997799,  0.75264406,  0.04782479, ...,  0.77456601,
         0.85449809,  0.40215379],
       [ 0.62021122,  0.11837821,  0.06605055, ...,  0.57107806,
         0.116174  ,  0.44576885],
       ..., 
       [ 0.31974984,  0.07513025,  0.33293656, ...,  0.90527885,
         0.6510998 ,  0.37642052],
       [ 0.39759161,  0.19708399,  0.6249228 , ...,  0.54417807,
         0.84909364,  0.32520673],
       [ 0.03514723,  0.45010126,  0.92401635, ...,  0.42907565,
         0.29463251,  0.53844834]])

In [18]:
f_array = np.asfortranarray(c_array)

In [19]:
f_array

array([[ 0.23998508,  0.11250528,  0.19466276, ...,  0.10422653,
         0.19806809,  0.27674198],
       [ 0.08997799,  0.75264406,  0.04782479, ...,  0.77456601,
         0.85449809,  0.40215379],
       [ 0.62021122,  0.11837821,  0.06605055, ...,  0.57107806,
         0.116174  ,  0.44576885],
       ..., 
       [ 0.31974984,  0.07513025,  0.33293656, ...,  0.90527885,
         0.6510998 ,  0.37642052],
       [ 0.39759161,  0.19708399,  0.6249228 , ...,  0.54417807,
         0.84909364,  0.32520673],
       [ 0.03514723,  0.45010126,  0.92401635, ...,  0.42907565,
         0.29463251,  0.53844834]])

In [20]:
x = np.array([1, 2, 3])

In [21]:
 y = np.array(['hello', 'world'])

In [23]:
x*2

array([2, 4, 6])