In [1]:
 sales = [1.0, 2.0, 3.5, 4.5, 5.0, 5.0, 4.5]

In [2]:
sales

[1.0, 2.0, 3.5, 4.5, 5.0, 5.0, 4.5]

In [5]:
sales *2

[1.0, 2.0, 3.5, 4.5, 5.0, 5.0, 4.5, 1.0, 2.0, 3.5, 4.5, 5.0, 5.0, 4.5]

In [4]:
sales + 2

TypeError: can only concatenate list (not "int") to list

In [6]:
import numpy as np

In [12]:
salesTwo = np.array(sales)

In [13]:
salesTwo

array([ 1. ,  2. ,  3.5,  4.5,  5. ,  5. ,  4.5])

In [14]:
print(sales)

[ 1.   2.   3.5  4.5  5.   5.   4.5]


In [15]:
sales * 2

array([  2.,   4.,   7.,   9.,  10.,  10.,   9.])

In [16]:
print(np.add(sales, 4))

[ 5.   6.   7.5  8.5  9.   9.   8.5]


In [17]:
sales

array([ 1. ,  2. ,  3.5,  4.5,  5. ,  5. ,  4.5])

# 3.2 Create arrays of data

In [18]:
import numpy as np

In [20]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [21]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [23]:
np.random.random(5)

array([ 0.47688369,  0.12006342,  0.74450684,  0.37088136,  0.89878676])

In [25]:
np.diag([1,2,3,5])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 5]])

In [26]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
np.linspace(1,100, 199)

array([   1. ,    1.5,    2. ,    2.5,    3. ,    3.5,    4. ,    4.5,
          5. ,    5.5,    6. ,    6.5,    7. ,    7.5,    8. ,    8.5,
          9. ,    9.5,   10. ,   10.5,   11. ,   11.5,   12. ,   12.5,
         13. ,   13.5,   14. ,   14.5,   15. ,   15.5,   16. ,   16.5,
         17. ,   17.5,   18. ,   18.5,   19. ,   19.5,   20. ,   20.5,
         21. ,   21.5,   22. ,   22.5,   23. ,   23.5,   24. ,   24.5,
         25. ,   25.5,   26. ,   26.5,   27. ,   27.5,   28. ,   28.5,
         29. ,   29.5,   30. ,   30.5,   31. ,   31.5,   32. ,   32.5,
         33. ,   33.5,   34. ,   34.5,   35. ,   35.5,   36. ,   36.5,
         37. ,   37.5,   38. ,   38.5,   39. ,   39.5,   40. ,   40.5,
         41. ,   41.5,   42. ,   42.5,   43. ,   43.5,   44. ,   44.5,
         45. ,   45.5,   46. ,   46.5,   47. ,   47.5,   48. ,   48.5,
         49. ,   49.5,   50. ,   50.5,   51. ,   51.5,   52. ,   52.5,
         53. ,   53.5,   54. ,   54.5,   55. ,   55.5,   56. ,   56.5,
      

In [69]:
np.ones(shape=(2,2,2), dtype='int')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [70]:
data = np.arange(9)

In [71]:
print(data)

[0 1 2 3 4 5 6 7 8]


In [75]:
data.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [82]:
newdata =data.reshape(3,3)

In [83]:
print(data)

[0 1 2 3 4 5 6 7 8]


In [84]:
newdata[0,0]=12
newdata[0,1]=13

In [85]:
newdata

array([[12, 13,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [92]:
print(newdata[1,:])

[3 4 5]


In [93]:
print(newdata[:,1])

[13  4  7]
