In [2]:
import numpy as np
x = np.arange(5,10)

In [3]:
x

array([5, 6, 7, 8, 9])

In [4]:
np.square(x)

array([25, 36, 49, 64, 81])

In [5]:
y = np.ones(5)

In [6]:
y

array([ 1.,  1.,  1.,  1.,  1.])

In [7]:
z = np.random.rand(20)

In [8]:
z

array([ 0.39938964,  0.3914784 ,  0.07184387,  0.9031198 ,  0.70420891,
        0.01625281,  0.85597248,  0.98162036,  0.17065058,  0.28464803,
        0.30975844,  0.58560839,  0.18833444,  0.04406644,  0.66693783,
        0.12837974,  0.86686457,  0.98783196,  0.14605824,  0.43807195])

In [9]:
z = z*10

In [10]:
z

array([ 3.99389638,  3.91478403,  0.71843869,  9.03119803,  7.04208908,
        0.16252806,  8.55972476,  9.81620358,  1.7065058 ,  2.84648031,
        3.09758441,  5.85608388,  1.88334439,  0.44066438,  6.66937829,
        1.2837974 ,  8.66864568,  9.87831964,  1.46058235,  4.38071953])

In [11]:
z = z*10

In [12]:
z

array([ 39.93896379,  39.14784032,   7.18438694,  90.31198026,
        70.42089084,   1.62528061,  85.5972476 ,  98.1620358 ,
        17.06505802,  28.46480315,  30.97584409,  58.56083885,
        18.83344389,   4.4066438 ,  66.69378291,  12.83797403,
        86.68645684,  98.78319639,  14.6058235 ,  43.80719528])

In [13]:
z.astype(int)

array([39, 39,  7, 90, 70,  1, 85, 98, 17, 28, 30, 58, 18,  4, 66, 12, 86,
       98, 14, 43])

In [14]:
z.mean()

45.705484345699048

In [15]:
z.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [16]:
z.max()

98.783196385907701

In [17]:
z.min()

1.625280614669633

In [18]:
z.sort()

In [19]:
z

array([  1.62528061,   4.4066438 ,   7.18438694,  12.83797403,
        14.6058235 ,  17.06505802,  18.83344389,  28.46480315,
        30.97584409,  39.14784032,  39.93896379,  43.80719528,
        58.56083885,  66.69378291,  70.42089084,  85.5972476 ,
        86.68645684,  90.31198026,  98.1620358 ,  98.78319639])

In [20]:
z=z.astype(int)

In [21]:
z

array([ 1,  4,  7, 12, 14, 17, 18, 28, 30, 39, 39, 43, 58, 66, 70, 85, 86,
       90, 98, 98])

In [22]:
nd = np.arange(9)

In [23]:
nd

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
nd = nd.reshape(3,3)

In [28]:
ndx

NameError: name 'ndx' is not defined

In [27]:
x = np.matrix(nd)

In [29]:
x

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [30]:
y = np.identity(3)y 

In [31]:
y

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [32]:
y = np.mat(np.identity(3))

In [33]:
y

matrix([[ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  1.]])