In [2]:
import numpy as np

In [3]:
ar1 = np.array([0,1,2,3])

In [7]:
ar2=np.array([[0,3,5],[2,8,7]])

In [10]:
ar1

array([0, 1, 2, 3])

In [11]:
ar2

array([[0, 3, 5],
       [2, 8, 7]])

In [13]:
ar2.ndim

2

In [14]:
ar3 = np.arange(12);ar3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
ar4=np.arange(3,10,3)

In [16]:
ar4

array([3, 6, 9])

In [17]:
ar5 = np.linspace(0,2.0/3,4)
ar5

array([ 0.        ,  0.22222222,  0.44444444,  0.66666667])